package androidCourse.technion.quickthumbs;

public class FirestoreConstants {
    public static final String usersCollection="users";
    public static final String textsCollection="texts";
    public static final String statsCollection="stats";
    public static final String statisticsDocument="statistics";
    public static final String gameResultsCollection="gameResults";

    //statistics fields
    public static final String uidField="uid";
    public static final String emailField="email";
    public static final String dateField ="lastUpdated";
    public static final String numOfGamesField="numOfGames";
    public static final String CPMField ="avgCPM";
    public static final String accuracyField ="avgAccuracy";
    public static final String WPMField ="avgWPM";
    public static final String totalScoreField = "TotalScore";
    public static final String textRatingField = "rating";
    public static final String themeField = "theme";
    public static final String textIndexField = "textIndex";
    public static final String textDateField = "date";
    public static final String numOfRatingsField = "numOfRatings";

    public static String transformBCP47CodeToLanguage(String code){
        switch (code){
            case "af": return "Afrikaans";
            case "am": return "Amharic";
            case "ar": return "Arabic";
            case "ar-Latn": return "Arabic";
            case "az": return "Azerbaijani";
            case "be": return "Belarusian";
            case "bg": return "Bulgarian";
            case "bg-Latn": return "Bulgarian";
            case "bn": return "Bengali";
            case "bs": return "Bosnian";
            case "ca": return "Catalan";
            case "ceb": return "Cebuano";
            case "co": return "Corsican";
            case "cs": return "Czech";
            case "cy": return "Welsh";
            case "da": return "Danish";
            case "de": return "German";
            case "el": return "Greek";
            case "el-Latn": return "Greek";
            case "en": return "English";
            case "eo": return "Esperanto";
            case "es": return "Spanish";
            case "et": return "Estonian";
            case "eu": return "Basque";
            case "fa": return "Persian";
            case "fi": return "Finnish";
            case "fil": return "Filipino";
            case "fr": return "French";
            case "fy": return "Western Frisian";
            case "ga": return "Irish";
            case "gd": return "Scots Gaelic";
            case "gl": return "Galician";
            case "gu": return "Gujarati";
            case "ha": return "Hausa";
            case "haw": return "Hawaiian";
            case "hi": return "Hindi";
            case "hi-Latn": return "Hindi";
            case "hmn": return "Hmong";
            case "hr": return "Croatian";
            case "ht": return "Haitian";
            case "hu": return "Hungarian";
            case "hy": return "Armenian";
            case "id": return "Indonesian";
            case "ig": return "Igbo";
            case "is": return "Icelandic";
            case "it": return "Italian";
            case "iw": return "Hebrew";
            case "ja": return "Japanese";
            case "ja-Latn": return "Japanese";
            case "jv": return "Javanese";
            case "ka": return "Georgian";
            case "kk": return "Kazakh";
            case "km": return "Khmer";
            case "kn": return "Kannada";
            case "ko": return "Korean";
            case "ku": return "Kurdish";
            case "ky": return "Kyrgyz";
            case "la": return "Latin";
            case "lb": return "Luxembourgish";
            case "lo": return "Lao";
            case "lt": return "Lithuanian";
            case "lv": return "Latvian";
            case "mg": return "Malagasy";
            case "mi": return "Maori";
            case "mk": return "Macedonian";
            case "ml": return "Malayalam";
            case "mn": return "Mongolian";
            case "mr": return "Marathi";
            case "ms": return "Malay";
            case "mt": return "Maltese";
            case "my": return "Burmese";
            case "ne": return "Nepali";
            case "nl": return "Dutch";
            case "no": return "Norwegian";
            case "ny": return "Nyanja";
            case "pa": return "Punjabi";
            case "pl": return "Polish";
            case "ps": return "Pashto";
            case "pt": return "Portuguese";
            case "ro": return "Romanian";
            case "ru": return "Russian";
            case "ru-Latn": return "Russian";
            case "sd": return "Sindhi";
            case "si": return "Sinhala";
            case "sk": return "Slovak";
            case "sl": return "Slovenian";
            case "sm": return "Samoan";
            case "sn": return "Shona";
            case "so": return "Somali";
            case "sq": return "Albanian";
            case "sr": return "Serbian";
            case "st": return "Sesotho";
            case "su": return "Sundanese";
            case "sv": return "Swedish";
            case "sw": return "Swahili";
            case "ta": return "Tamil";
            case "te": return "Telugu";
            case "tg": return "Tajik";
            case "th": return "Thai";
            case "tr": return "Turkish";
            case "uk": return "Ukrainian";
            case "ur": return "Urdu";
            case "uz": return "Uzbek";
            case "vi": return "Vietnamese";
            case "xh": return "Xhosa";
            case "yi": return "Yiddish";
            case "yo": return "Yoruba";
            case "zh": return "Chinese";
            case "zh-Latn": return "Chinese";
            case "zu": return "Zulu";

        }
        return "English";
    }

    public static String transformBCP47CodeToScript(String code){
        switch (code){
            case "af": return "Latin";
            case "am": return "Ge'ez";
            case "ar": return "Arabic";
            case "ar-Latn": return "Latin";
            case "az": return "Latin";
            case "be": return "Cyrillic";
            case "bg": return "Cyrillic";
            case "bg-Latn": return "Latin";
            case "bn": return "Bengali";
            case "bs": return "Latin";
            case "ca": return "Latin";
            case "ceb": return "Latin";
            case "co": return "Latin";
            case "cs": return "Latin";
            case "cy": return "Latin";
            case "da": return "Latin";
            case "de": return "Latin";
            case "el": return "Greek";
            case "el-Latn": return "Latin";
            case "en": return "Latin";
            case "eo": return "Latin";
            case "es": return "Latin";
            case "et": return "Latin";
            case "eu": return "Latin";
            case "fa": return "Arabic";
            case "fi": return "Latin";
            case "fil": return "Latin";
            case "fr": return "Latin";
            case "fy": return "Latin";
            case "ga": return "Latin";
            case "gd": return "Latin";
            case "gl": return "Latin";
            case "gu": return "Gujarati";
            case "ha": return "Latin";
            case "haw": return "Latin";
            case "hi": return "Devanagari";
            case "hi-Latn": return "Latin";
            case "hmn": return "Latin";
            case "hr": return "Latin";
            case "ht": return "Latin";
            case "hu": return "Latin";
            case "hy": return "Armenian";
            case "id": return "Latin";
            case "ig": return "Latin";
            case "is": return "Latin";
            case "it": return "Latin";
            case "iw": return "Hebrew";
            case "ja": return "Japanese";
            case "ja-Latn": return "Latin";
            case "jv": return "Latin";
            case "ka": return "Georgian";
            case "kk": return "Cyrillic";
            case "km": return "Khmer";
            case "kn": return "Kannada";
            case "ko": return "Korean";
            case "ku": return "Latin";
            case "ky": return "Cyrillic";
            case "la": return "Latin";
            case "lb": return "Latin";
            case "lo": return "Lao";
            case "lt": return "Latin";
            case "lv": return "Latin";
            case "mg": return "Latin";
            case "mi": return "Latin";
            case "mk": return "Cyrillic";
            case "ml": return "Malayalam";
            case "mn": return "Cyrillic";
            case "mr": return "Devanagari";
            case "ms": return "Latin";
            case "mt": return "Latin";
            case "my": return "Myanmar";
            case "ne": return "Devanagari";
            case "nl": return "Latin";
            case "no": return "Latin";
            case "ny": return "Latin";
            case "pa": return "Gurmukhi";
            case "pl": return "Latin";
            case "ps": return "Arabic";
            case "pt": return "Latin";
            case "ro": return "Latin";
            case "ru": return "Cyrillic";
            case "ru-Latn": return "English";
            case "sd": return "Arabic";
            case "si": return "Sinhala";
            case "sk": return "Latin";
            case "sl": return "Latin";
            case "sm": return "Latin";
            case "sn": return "Latin";
            case "so": return "Latin";
            case "sq": return "Latin";
            case "sr": return "Cyrillic";
            case "st": return "Latin";
            case "su": return "Latin";
            case "sv": return "Latin";
            case "sw": return "Latin";
            case "ta": return "Tamil";
            case "te": return "Telugu";
            case "tg": return "Cyrillic";
            case "th": return "Thai";
            case "tr": return "Latin";
            case "uk": return "Cyrillic";
            case "ur": return "Arabic";
            case "uz": return "Latin";
            case "vi": return "Latin";
            case "xh": return "Latin";
            case "yi": return "Hebrew";
            case "yo": return "Latin";
            case "zh": return "Chinese";
            case "zh-Latn": return "Latin";
            case "zu": return "Latin";


        }
        return "Latin";
    }
}
